---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 'https://api.stackbit.com/project/6004679afdd57c0015a0906d/webhook/forestry'
sections:
- type: document
  path: config.yaml
  label: Global site config
  templates:
  - config
- type: document
  path: content/_index.md
  label: Home
  templates:
  - home
- type: document
  path: content/store.md
  label: Store
  templates:
  - store
- type: directory
  path: content
  label: Pages
  create: all
  match: '**/*'
  new_doc_ext: md
  templates:
  - advanced
  - category
  - product
upload_dir: static/images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
version: '0.48'
